import Head from 'next/head'
import Footer from "../components/footer";
import HeaderBG from "../components/header_bg";
import MintBasics from "../components/howTo";
import GettingStarted from "../components/started";

const Home = () => {

  return (
    <div>
      <Head>
        <title>Ibex Dao</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderBG />
      <GettingStarted />
      <MintBasics />
      <Footer />
    </div >
  );
};

export default Home;
